export default {
  suasana_positif_dan_damai: [
    "senang",
    "bahagia",
    "gembira",
    "tertawa",
    "baik",
    "puas",
    "setuju",
    "setuju dengan pendapat anda",
    "baik-baik saja",
    "mantap",
    "bagus",
    "semangat",
  ],
  suasana_sedih: [
    "sedih",
    "kecewa",
    "murung",
    "menangis",
    "patah hati",
    "melelahkan",
  ],
  suasana_menegangkan: [
    "marah",
    "kesal",
    "benci",
    "emosi",
    "geram",
    "tidak suka",
    "tidak setuju",
    "bodoh",
    "aneh",
    "sial",
    "menjengkelkan",
    "menyebalkan",
    "mengecewakan",
    "menyakitkan",
    "menyusahkan",
    "merugikan",
  ],
  suasana_netral: [
    "biasa",
    "netral",
    "tenang",
    "terima kasih",
    "santai",
    "oke",
  ],
  suasana_takut: ["takut", "cemas", "khawatir", "panik"],
  suasana_terkejut: ["terkejut", "kaget", "heran", "tidak menyangka"],
};
// This module exports an object containing arrays of keywords associated with different emotions.
